### ISSUE TITLE
MPU9250 configuration

### ISSUE THREAD

**Issue by YuriBittencourt** [davidssand/Starla#7]
The sensor is not configurated with the right "G" scale to use, hence it's not reading it right.
possible solution is to set it in its I2C communication.

This [link](https://github.com/tuupola/micropython-mpu9250/blob/master/mpu6500.py) might help

**Comment by YuriBittencourt** [comment]
After some research, @JunHats and I discovered how to set the acceleration scale.
This line below should fix it:
```python
self.bus.write_byte_data(self.address, 0x1C, 0x18)
```

However I am still not so sure about it, the new acceleration graphic is as follow:

![image](https://user-images.githubusercontent.com/28678662/76897522-ac083180-6872-11ea-9675-dc0493f2eca2.png)

EDIT:
We found all the adresses of the registers [here](https://cdn.sparkfun.com/assets/learn_tutorials/5/5/0/MPU-9250-Register-Map.pdf) in section 3
The value used ``` 0x18 ``` is to set to 16G scale, if we were to set it to 8G, 4G or 2G we would use ```0x10 ```, ```0x8 ``` and ``` 0x0 ``` respectively instead.

**Comment by davidssand** [comment]
Good job! I will just suggest you to experiment reading above 2G's(previous saturation value) to see if it really worked.

**Comment by YuriBittencourt** [comment]
Moved issue to new Repo [here](https://github.com/Apex-Rocketry/Starla/issues/1)
